#### assuming this is a fresh VM --> following is a standard syntax
#trigger for this code to run is whenever something is added to main
name: Terraform Deployment

# when we git push succeessfully, this will run
on: #defined word from git
  push: 
    branches:
      - main

# declare the running agent 
jobs: #defined words
 terraform: #variable name
   runs-on: ubuntu-latest

   steps:

#git clone/git checkout
   - name: Checkout repository
     uses: actions/checkout@v2

#aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1 # or hardcode us-east-1

#install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

#terraform init
   - name: Initialize Terraform
     run: terraform init

#terraform apply
   - name: Terraform Apply
     run: terraform apply --auto-approve